/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RunParams {
  currentDir: string;
  targetDir: string;
}
/** The main entry of this napi package. */
export function run(args: Array<string>, params: RunParams): void;
